name: comment-on-terraform-plan

on:
  pull_request:
    types: [opened]

jobs:
  plan:
    name: Terraform Plan
    runs-on:
      - self-hosted
      - terraform-1.0
    outputs:
      modified_terraform: ${{ steps.plan.outputs.modified_terraform }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Terragrunt plan
        run: |
          terragrunt run-all plan > logs.txt
          echo "##[set-output name=modified_terraform;]$(cat logs.txt | grep "No changes. Infrastructure is up-to-date." || true)"
        id: plan
        env:
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          ENVIRONMENT: prod
          BRANCH: master
          TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  pullRequestComment:
    runs-on: ubuntu-latest
    needs:
      - plan
    steps:
      - name: Pull Request Comment
        if: contains( ${{ needs.plan.outputs.modified_terraform }}, "No changes. Infrastructure is up-to-date.")
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "This PR will modify the currently deployed application in Azure"
