name: verify/dotnet

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  test:
    runs-on:
      - self-hosted
      - dotnet-sdk-3.1
    steps:
      - uses: actions/checkout@v1

      - run: |
          dotnet run -p build/build.csproj -- test
          bash <(curl -s https://codecov.io/bash)
