name: preview-destroy

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    runs-on:
      - self-hosted
      - terraform-1.0
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terragrunt Destroy
        run: yes | terragrunt run-all destroy
        working-directory: ./terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          ENVIRONMENT: preview
          BRANCH: ${{ github.head_ref }}
          TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
